insert ignore into user(username,password,role) values('user@user.com','$2a$10$fFHaNo7/UMh7rtp3LAjH0e2ZcoI2a7Ju.TUdWt.Nc52iWN1OkALkC','ROLE_USER')
insert ignore into user(username,password,role) values('user2@user2.com','$2a$10$fFHaNo7/UMh7rtp3LAjH0e2ZcoI2a7Ju.TUdWt.Nc52iWN1OkALkC','ROLE_USER')
insert ignore into user(username,password,role) values('user3@user3.com','$2a$10$fFHaNo7/UMh7rtp3LAjH0e2ZcoI2a7Ju.TUdWt.Nc52iWN1OkALkC','ROLE_USER')
insert ignore into user(username,password,role) values('user4@user4.com','$2a$10$fFHaNo7/UMh7rtp3LAjH0e2ZcoI2a7Ju.TUdWt.Nc52iWN1OkALkC','ROLE_USER')
insert ignore into user(username,password,role) values('admin@admin.com','$2a$10$fFHaNo7/UMh7rtp3LAjH0e2ZcoI2a7Ju.TUdWt.Nc52iWN1OkALkC','ROLE_ADMIN')